language: python
python:
    - "3.8"
install:
    - pip install -r requirements.txt
before_script:
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
script:
    - python -m unittest discover -s tests